DATASET:
  TYPE: 'KITTI'
  POINT_CLOUD_RANGE: (-40, 40, -5, 3, 0, 70)
  KITTI:
    CLS_LIST: ('Car', )                                                                                                                
    BASE_DIR_PATH: 'dataset/KITTI/object'                                                                     
    TRAIN_LIST: 'dataset/KITTI/object/train.txt'                                                              
    VAL_LIST: 'dataset/KITTI/object/val.txt'                                                                  
    SAVE_NUMPY_PATH: 'dataset/3DSSD/data/KITTI'
TRAIN:
  AUGMENTATIONS:
    OPEN: True
    FLIP: True
    MIXUP:
      OPEN: True
      SAVE_NUMPY_PATH: 'mixup_database/KITTI'
      PC_LIST: 'train'
      CLASS: ('Car', )
      NUMBER: (15, )
  CONFIG:
    # BATCH_SIZE: 4
    # GPU_NUM: 2
    BATCH_SIZE: 8
    GPU_NUM: 1
    MAX_ITERATIONS: 80700 
    CHECKPOINT_INTERVAL: 807
    SUMMARY_INTERVAL: 10
SOLVER:
  TYPE: 'Adam'
  BASE_LR: 0.002
  STEPS: [64560]
TEST:
  WITH_GT: True
  TEST_MODE: 'mAP'
DATA_LOADER:
  NUM_THREADS: 8 # GPU_NUM x BATCH_SIZE
MODEL:
  POINTS_NUM_FOR_TRAINING: 16384
  TYPE: 'SingleStage'
  ANGLE_CLS_NUM: 12
  MAX_TRANSLATE_RANGE: [-3.0, -2.0, -3.0]
  # backbones
  NETWORK:
    SYNC_BN: False
    USE_GN: False
    AGGREGATION_SA_FEATURE: True
    FIRST_STAGE:
      ARCHITECTURE: [
        [[0], [0], [0.2,0.4,0.8], [32,32,64], [[16,16,32], [16,16,32], [32,32,64]], True,
         [-1], ['D-FPS'], [4096],
         -1, False, 'SA_Layer', 'layer1', True, -1, 64], # layer1
        [[1], [1], [0.4,0.8,1.6], [32,32,64], [[64,64,128], [64,64,128], [64,96,128]], True,
         [-1], ['FS'], [512],
         -1, False, 'SA_Layer', 'layer2', True, -1, 128], # layer2
        [[2], [2], [1.6,3.2,4.8], [32,32,32], [[128,128,256], [128,192,256], [128,256,256]], True,
         [512, -1], ['F-FPS', 'D-FPS'], [256, 256],
         -1, False, 'SA_Layer', 'layer3', True, -1, 256], # layer3 
        # vote
        [[3], [3], [], [], [], True,
         [256, -1], ['F-FPS', 'D-FPS'], [256, 0],
         -1, False, 'SA_Layer', 'vote', False, -1, 256],
        [[4], [4], -1, -1, [128,], True,
         [-1], [-1], [-1],
         -1, -1, 'Vote_Layer', 'vote', False, -1, -1], # layer3-vote
        # CG layer
        [[3], [3], [4.8, 6.4], [16, 32], [[256,256,512], [256,512,1024]], True,
         [-1], ['D-FPS'], [256],
         -1, False, 'SA_Layer', 'layer4', False, 5, 512], # layer4
      ]
      HEAD: [[[6], [6], 'conv1d', [128,], True, 'Det', '']]
  FIRST_STAGE: 
    MAX_OUTPUT_NUM: 100 
    NMS_THRESH: 0.1
    MINIBATCH_NUM: -1
    REGRESSION_METHOD: 
      TYPE: 'Dist-Anchor-free'
    CLS_ACTIVATION: 'Sigmoid'
    ASSIGN_METHOD: 'Mask'
    CORNER_LOSS: True
    CLASSIFICATION_LOSS:
      TYPE: 'Center-ness'
      SOFTMAX_SAMPLE_RANGE: 10.0
    
